"""Synthetic SQ01 regressions: native search only, durable failures and frozen outputs.

Fake transports supply inspectable bytes. No expected-publication input is opened.
The few actual repository reads are source/configuration or byte-only preservation
checks; historical discovery output is never regenerated by these tests.
"""
import copy
from contextlib import redirect_stderr, redirect_stdout
import io
import json
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest
from unittest.mock import patch
from urllib.parse import parse_qs, urlsplit

from deathmap_ai import discovery_sq01 as cli
from deathmap_ai import sq01_omicsdi as omics
from deathmap_ai import sq01_orcs as orcs
from deathmap_ai import sq01_export as projection
from deathmap_ai import sq01_plan as config
from deathmap_ai import sq01_io as disk
from deathmap_ai.sq01_transport import validate_url


def response(rows=None, count=0, code=200, headers=None):
    return {'http_status':code,'headers':headers or {},'body':json.dumps({'count':count,'datasets':rows or []}).encode()}


def native(identifier='synthetic-a', repository='synthetic-repository'):
    return {'source':repository,'id':identifier,'title':'Synthetic title','description':'Original synthetic description'}


def screen(identifier, publication, text):
    return {'SCREEN_ID':identifier,'SOURCE_TYPE':'pubmed','SOURCE_ID':publication,
        'SCREEN_NAME':'Synthetic screen','SCREEN_FORMAT':'pooled','METHODOLOGY':'CRISPR',
        'NOTES':text,'AUTHOR':'synthetic citation','CELL_LINE':'synthetic line'}


class SQ01Tests(unittest.TestCase):
    def setUp(self):
        self.tmp=tempfile.TemporaryDirectory();self.addCleanup(self.tmp.cleanup)
        self.root=Path(self.tmp.name);self.folder=self.root/'omics';self.folder.mkdir()
        self.plan=config.build_plan();self.digest=config.digest(self.plan)
        self.state=omics.initial(self.digest)
        self.qids=list(self.state['queries']);self.queries=self.plan['resources'][0]['queries']
        self.calls=[];self.sleeps=[]

    def run_engine(self, fetch=None, state=None):
        callback=fetch or (lambda *args:response())
        def record(url,timeout):
            self.calls.append(url)
            return callback(url,timeout)
        return omics.run(self.folder,state or self.state,self.digest,record,self.sleeps.append,emit=lambda _:None)

    def index(self, rows):
        disk.write(self.root/config.INDEX,rows)
        disk.write(self.root/config.INDEX_SUMMARY,{'screens_retrieved':len(rows),'retrieved_at':'original-cache-date'})

    def test_exact_question_family_and_disabled_stages(self):
        self.assertEqual(self.plan['scientific_questions'],[{'question_id':'SQ01','question':'pooled CRISPR knockout screens in cancer cells under immune selection'}])
        expected=[
            'pooled AND CRISPR AND knockout AND screens AND "cancer cells" AND immune AND selection',
            'CRISPR AND knockout AND "cancer cells" AND immune',
            'pooled AND CRISPR AND knockout AND screen AND "cancer cells" AND immune AND selection',
            'pooled AND CRISPR AND knockout AND screens AND "cancer cell" AND immune AND selection',
            'pooled AND CRISPR AND knockout AND screens AND "tumor cell" AND immune AND selection',
            'pooled AND CRISPR AND knockout AND "cancer cells" AND coculture',
            'pooled AND CRISPR AND knockout AND "cancer cells" AND co-culture',
            'pooled AND CRISPR AND knockout AND "cancer cells" AND "co culture"',
            'pooled AND CRISPR AND knockout AND "cancer cells" AND "immune killing"',
            'pooled AND CRISPR AND knockout AND "cancer cells" AND "immune pressure"',
            'pooled AND CRISPR AND knockout AND "cancer cells" AND "immune selection"']
        self.assertEqual([q['submitted_query'] for q in self.queries],expected)
        self.assertEqual(self.qids,[f'OM3-SQ01-Q{i:02}' for i in range(1,12)])
        self.assertEqual(len(set(self.qids)),11)
        self.assertTrue(all(q['scientific_question_ids']==['SQ01'] for q in self.queries))
        self.assertNotIn('CRISPR AND screen AND cancer AND immune',expected)
        self.assertFalse(self.plan['resources'][0]['interface']['detail_requests_enabled'])
        self.assertEqual(self.plan,config.build_plan())

    def test_plan_digest_and_cap_mutations_rejected(self):
        for field in ('candidate_cap','page_cap','runtime_cap'):
            bad=copy.deepcopy(self.plan);bad['resources'][0]['limits'][field]=1
            with self.assertRaises(ValueError):config.validate_plan(bad)
        with self.assertRaises(ValueError):omics.run(self.folder,self.state,'wrong',lambda *a:self.fail('network'))
        bad=copy.deepcopy(self.plan);bad['resources'][0]['queries'][0]['submitted_query']='CRISPR AND screen AND cancer AND immune'
        with self.assertRaises(ValueError):config.validate_plan(bad)

    def test_sequential_independent_pagination_duplicates_and_totals(self):
        def fetch(url,timeout):
            p=parse_qs(urlsplit(url).query);query=p['query'][0];offset=int(p['start'][0])
            self.assertEqual(timeout,20);self.assertEqual(p['size'],['50'])
            if query==self.queries[0]['submitted_query']:
                return response([native('a'),native('a')],4) if offset==0 else response([native('b')],3)
            if query==self.queries[1]['submitted_query']:return response([native('a')],1)
            return response()
        self.run_engine(fetch)
        order=[parse_qs(urlsplit(u).query)['query'][0] for u in self.calls]
        self.assertEqual(order[:3],[self.queries[0]['submitted_query']]*2+[self.queries[1]['submitted_query']])
        counts=omics.summary(self.state);first=counts['queries'][self.qids[0]]
        self.assertEqual(first['pages'],2);self.assertEqual(first['observations'],3)
        self.assertEqual(first['unique_records'],2);self.assertEqual(first['duplicate_observations_within_query'],1)
        self.assertEqual(first['overlap_with_other_queries'],1);self.assertEqual(first['exclusive_to_query'],1)
        self.assertEqual(counts['unique_records'],2);self.assertEqual(counts['observations'],4)
        self.assertIn('reported_total_changed',[x['type'] for x in self.state['issues']])
        self.assertEqual(self.state['status'],'complete')

    def test_empty_page_and_reported_total_exhaustion(self):
        self.run_engine()
        self.assertEqual(len(self.calls),11)
        self.assertTrue(all(q['status']=='exhausted' and q['offset']==0 for q in self.state['queries'].values()))
        self.assertEqual(omics.summary(self.state)['query_status_groups']['complete'],self.qids)

    def test_no_candidate_cap_even_when_service_returns_large_page(self):
        many=[native(str(i)) for i in range(5001)]
        self.run_engine(lambda url,t:response(many,5001) if parse_qs(urlsplit(url).query)['query'][0]==self.queries[0]['submitted_query'] else response())
        self.assertEqual(len(self.state['records']),5001)
        self.assertEqual(self.state['queries'][self.qids[0]]['offset'],5001)
        self.assertEqual(self.state['queries'][self.qids[0]]['buffer'],[])

    def test_no_page_cap(self):
        def fetch(url,t):
            p=parse_qs(urlsplit(url).query);offset=int(p['start'][0])
            return response([native(str(offset))],12) if p['query'][0]==self.queries[0]['submitted_query'] else response()
        self.run_engine(fetch)
        self.assertEqual(len(self.state['queries'][self.qids[0]]['pages']),12)
        self.assertEqual(self.state['status'],'complete')

    def test_native_repository_pairs_are_not_merged(self):
        rows=[native('same','repo-A'),native('same','repo-B')]
        self.run_engine(lambda url,t:response(rows,2) if not self.state['observations'] else response())
        self.assertEqual(len(self.state['records']),2)
        self.assertEqual(omics.summary(self.state)['native_repository_counts'],{'repo-A':1,'repo-B':1})

    def test_invalid_identity_preserves_complete_raw_and_buffer(self):
        rows=[native(),{'source':'synthetic','id':'a','database':'different','accession':'b'},native('later')]
        self.run_engine(lambda url,t:response(rows,3) if self.qids[0] in url or len(self.calls)==1 else response())
        first=self.state['queries'][self.qids[0]]
        self.assertEqual(first['status'],'blocked');self.assertEqual(len(first['buffer']),2)
        self.assertEqual(len(self.state['records']),1)
        event=self.state['attempts'][0]
        self.assertEqual(disk.read(self.folder/event['raw_file'])['datasets'],rows)
        self.assertEqual(first['block_reason'],'invalid_native_identity')

    def test_unrecognized_payload_is_not_empty_exhaustion(self):
        self.run_engine(lambda url,t: {'http_status':200,'headers':{},'body':b'{"wrong": []}'} if len(self.calls)==1 else response())
        self.assertEqual(self.state['queries'][self.qids[0]]['status'],'blocked')
        self.assertEqual(self.state['status'],'partial')

    def test_reserved_checkpoint_precedes_transport(self):
        def fetch(url,t):
            saved=disk.read(self.folder/'resume_state.json')
            self.assertEqual(saved['attempts'][-1]['status'],'reserved')
            self.assertEqual(saved['attempts'][-1]['url'],url)
            return response()
        self.run_engine(fetch)

    def test_uncertain_transport_not_retried_on_resume(self):
        def fetch(url,t):
            if len(self.calls)==1:raise TimeoutError('synthetic uncertainty')
            return response()
        self.run_engine(fetch)
        self.assertEqual(self.state['queries'][self.qids[0]]['status'],'blocked')
        before=len(self.calls);loaded=disk.read(self.folder/'resume_state.json')
        self.run_engine(state=loaded)
        self.assertEqual(len(self.calls),before)
        self.assertEqual(loaded['attempts'][0]['status'],'uncertain')

    def test_reservation_without_outcome_blocks_after_interruption(self):
        def fetch(*args):raise KeyboardInterrupt()
        with self.assertRaises(KeyboardInterrupt):self.run_engine(fetch)
        loaded=disk.read(self.folder/'resume_state.json')
        self.assertEqual(loaded['attempts'][0]['status'],'reserved')
        self.run_engine(state=loaded)
        self.assertEqual(loaded['queries'][self.qids[0]]['block_reason'],'reserved_without_durable_outcome')
        self.assertEqual(sum(e['query_id']==self.qids[0] for e in loaded['attempts']),1)

    def test_two_http_attempts_cumulative_and_body_preserved(self):
        self.run_engine(lambda url,t:response(code=500) if len(self.calls)<=2 else response())
        first=self.state['queries'][self.qids[0]]
        self.assertEqual(first['status'],'failed')
        self.assertEqual(sum(e['query_id']==self.qids[0] for e in self.state['attempts']),2)
        self.assertIn(2,self.sleeps)
        before=len(self.calls);self.run_engine(state=disk.read(self.folder/'resume_state.json'))
        self.assertEqual(len(self.calls),before)
        self.assertTrue((self.folder/self.state['attempts'][0]['raw_file']).exists())

    def test_three_failures_stop_invocation_and_resume_keeps_attempts(self):
        self.run_engine(lambda *args:response(code=500))
        self.assertEqual(len(self.calls),3)
        self.assertEqual(self.state['queries'][self.qids[0]]['status'],'failed')
        self.assertEqual(self.state['queries'][self.qids[1]]['status'],'running')
        loaded=disk.read(self.folder/'resume_state.json');self.run_engine(state=loaded)
        self.assertEqual(sum(e['query_id']==self.qids[1] for e in loaded['attempts']),2)
        self.assertEqual(loaded['queries'][self.qids[1]]['status'],'exhausted')
        self.assertEqual(loaded['queries'][self.qids[0]]['status'],'failed')

    def test_throttling_honors_delay_or_blocks_long_pause(self):
        self.run_engine(lambda url,t:response(code=429,headers={'Retry-After':'120'}) if len(self.calls)==1 else response())
        self.assertEqual(self.state['queries'][self.qids[0]]['block_reason'],'service_retry_delay_requires_review')
        self.assertEqual(sum(e['query_id']==self.qids[0] for e in self.state['attempts']),1)

    def test_checkpoint_failure_prevents_request(self):
        original=omics.checkpoint
        def save(folder,state):
            if state['attempts']:raise PermissionError('synthetic failed reservation checkpoint')
            original(folder,state)
        with patch.object(omics,'checkpoint',side_effect=save),self.assertRaises(PermissionError):
            self.run_engine(lambda *args:self.fail('request before durable checkpoint'))
        self.assertEqual(self.calls,[])

    def test_durable_receipt_recovers_without_repeating_request(self):
        original=omics.checkpoint
        def save(folder,state):
            if state['attempts'] and state['attempts'][-1]['status']=='received':
                raise PermissionError('synthetic post-receipt checkpoint interruption')
            original(folder,state)
        with patch.object(omics,'checkpoint',side_effect=save),self.assertRaises(PermissionError):self.run_engine()
        loaded=disk.read(self.folder/'resume_state.json')
        self.assertEqual(loaded['attempts'][0]['status'],'reserved')
        self.run_engine(state=loaded)
        self.assertEqual(sum(e['query_id']==self.qids[0] for e in loaded['attempts']),1)
        self.assertEqual(loaded['status'],'complete')

    def test_repeated_nonempty_page_blocks_instead_of_looping(self):
        self.run_engine(lambda url,t:response([native()],100) if parse_qs(urlsplit(url).query)['query'][0]==self.queries[0]['submitted_query'] else response())
        self.assertEqual(len(self.state['queries'][self.qids[0]]['pages']),2)
        self.assertEqual(self.state['queries'][self.qids[0]]['block_reason'],'repeated_nonempty_page')

    def test_transport_rejects_details_enrichment_and_abandoned_query(self):
        for url in ['https://www.omicsdi.org/ws/dataset/geo/synthetic', 'https://example.org/',
                    config.ENDPOINT+'?query=CRISPR+AND+screen+AND+cancer+AND+immune&start=0&size=50']:
            with self.assertRaises(ValueError):validate_url(url)
        for q in self.queries:validate_url(omics.search_url(q,0))
        self.run_engine()
        self.assertTrue(all(urlsplit(url).path=='/ws/dataset/search' for url in self.calls))
        self.assertTrue(all(e['kind']=='search' for e in self.state['attempts']))

    def test_orcs_complete_index_field_evidence_and_siblings(self):
        text='POOLED CRISPR knockout screens screen cancer cells cancer cell tumor cell immune selection coculture co-culture co culture immune killing immune pressure'
        rows=[screen('synthetic-screen-a','synthetic-paper-a',text),screen('synthetic-screen-b','synthetic-paper-a','context only'),screen('synthetic-screen-c','synthetic-paper-b','unrelated')]
        rows[2]['AUTHOR']=text  # Excluded fields must not trigger a match.
        self.index(rows);state=orcs.initial(self.digest);folder=self.root/'orcs'
        with patch.object(orcs,'match_row',wraps=orcs.match_row) as matcher:
            orcs.run(self.root,folder,state,self.digest)
            self.assertEqual(matcher.call_count,3)
            orcs.run(self.root,folder,state,self.digest)
            self.assertEqual(matcher.call_count,3)
        self.assertEqual(state['counts']['examined_screens'],3)
        self.assertEqual(state['counts']['direct_matches'],1);self.assertEqual(state['counts']['publication_siblings'],1)
        self.assertEqual({h['query_id'] for h in state['query_hits']},{f'OR3-SQ01-Q{i:02}' for i in range(1,12)})
        for hit in state['query_hits']:
            self.assertIn(hit['source_field_name'],config.FIELDS)
            self.assertEqual(hit['source_field_value'],rows[0][hit['source_field_name']])
            self.assertEqual(hit['normalized_comparison_form'],hit['source_field_value'].casefold())
            self.assertTrue(hit['direct_match']);self.assertEqual(hit['scientific_question_id'],'SQ01')
        sibling=next(c for c in state['candidates'] if not c['direct_match'])
        self.assertEqual(sibling['query_ids'],[]);self.assertTrue(sibling['parent_match_references'])
        projection.export(self.root,folder,state);projection.export(self.root,folder,state,verify=True)
        self.assertTrue((folder/'freeze_manifest.json').exists())

    def test_missing_orcs_cache_fails_without_refresh(self):
        state=orcs.initial(self.digest)
        orcs.run(self.root,self.root/'orcs',state,self.digest)
        self.assertEqual(state['status'],'failed');self.assertTrue(state['issues'])

    def test_optional_orcs_notes_can_be_absent(self):
        row=screen('synthetic-no-notes','synthetic-paper','unused');del row['NOTES']
        self.index([row]);state=orcs.initial(self.digest)
        orcs.run(self.root,self.root/'orcs',state,self.digest)
        self.assertEqual(state['status'],'complete')
        self.assertEqual(state['counts']['examined_screens'],1)
        self.assertNotIn('NOTES',state['source_records'][0]['native_metadata'])

    def test_unrecognized_orcs_schema_fails(self):
        self.index([{'SCREEN_ID':'synthetic'}]);state=orcs.initial(self.digest)
        orcs.run(self.root,self.root/'orcs',state,self.digest)
        self.assertEqual(state['status'],'failed')

    def test_offline_exports_freeze_and_native_fields_preserved(self):
        row=native();row['unfamiliar']={'nested':['synthetic-value']}
        self.run_engine(lambda url,t:response([row],1) if len(self.calls)==1 else response())
        projection.export(self.root,self.folder,self.state)
        snapshot={p:disk.sha(p) for p in self.folder.rglob('*') if p.is_file()}
        projection.export(self.root,self.folder,self.state,verify=True)
        self.run_engine(state=disk.read(self.folder/'resume_state.json'))
        self.assertEqual(snapshot,{p:disk.sha(p) for p in snapshot})
        output=disk.read(self.folder/'source_records.json')['records'][0]['native_metadata']
        self.assertEqual(output,row)
        self.assertFalse(any((self.folder/name).exists() for name in ('datasets.json','publications.json','screens.json','output.xlsx')))
        disk.write(self.folder/'unexpected.json',{})
        with self.assertRaises(ValueError):disk.verify_freeze(self.folder,self.digest)

    def test_os_lock_rejects_second_writer(self):
        with disk.writer_lock(self.root):
            with self.assertRaises(RuntimeError):
                with disk.writer_lock(self.root):pass
        with disk.writer_lock(self.root):pass

    def test_atomic_replace_retries_are_bounded(self):
        with patch.object(disk.os,'replace',side_effect=PermissionError('locked')) as replace,patch.object(disk.time,'sleep'):
            with self.assertRaises(PermissionError):disk.write(self.root/'checkpoint.json',{})
        self.assertEqual(replace.call_count,5)
        self.assertTrue((self.root/'checkpoint.json.tmp').exists())

    def test_refusal_of_entity_excel_and_detail_actions(self):
        for action in ('details','enrich','project','excel','evaluate'):
            with redirect_stderr(io.StringIO()),self.assertRaises(SystemExit):cli.main([action,'--root',str(self.root)])
        self.assertFalse((self.root/'outputs').exists())

    def test_cli_prepare_preflight_run_freeze_and_verify_offline(self):
        self.index([screen('synthetic-screen','synthetic-paper','unrelated')])
        historical=self.root/'outputs/synthetic-v01/manifest.json'
        disk.write(historical,{'historical':'unchanged'})
        baseline={p.relative_to(self.root).as_posix():disk.sha(p) for p in [historical,self.root/config.INDEX,self.root/config.INDEX_SUMMARY]}
        disk.write(self.root/'docs/sq01-preservation.json',{'recorded_at':'synthetic-date','before':baseline})
        proposal={'plan_version':'immune-crispr-coculture-v03.1','status':'proposed_for_owner_review','synthetic':'prior review'}
        shared=self.root/'outputs'/config.VERSION
        disk.write(shared/'query_plan.json',proposal)
        with disk.writer_lock(self.root):
            cli.prepare(self.root)
        self.assertEqual(disk.read(shared/'planning-history/query_plan-proposed-v03.1.json'),proposal)
        with patch.object(cli.subprocess,'run',return_value=subprocess.CompletedProcess([],0,'','Synthetic offline suite passed')):
            cli.preflight(self.root)
        original=omics.run
        def fake_run(folder,state,plan_digest):
            return original(folder,state,plan_digest,lambda *a:response(),sleep=lambda _:None,emit=lambda _:None)
        with patch.object(cli.omics,'run',side_effect=fake_run):
            value,code=cli.execute(self.root,'run','all')
        self.assertEqual(code,0);self.assertEqual(value['status'],'complete')
        self.assertTrue((shared/'run_freeze.json').is_file())
        with redirect_stdout(io.StringIO()):
            self.assertEqual(cli.main(['verify','--root',str(self.root)]),0)
        self.assertEqual(disk.preservation(self.root)['changed_files'],[])
        disk.write(self.root/'src/synthetic.py',{'change':'invalidate preflight'})
        with self.assertRaisesRegex(ValueError,'Preflight'):
            cli.require_preflight(self.root,self.digest)

    def test_foreign_output_and_uncommitted_checkpoint_block_preflight(self):
        folder=self.root/'outputs/omicsdi'/config.VERSION
        disk.write(folder/'foreign.json',{})
        with self.assertRaises(ValueError):cli.check_directories(self.root,self.digest)
        (folder/'foreign.json').unlink()
        disk.write(folder/'resume_state.json',self.state)
        disk.write(folder/'resume_state.json.tmp',self.state)
        with self.assertRaisesRegex(ValueError,'uncommitted'):
            cli.check_directories(self.root,self.digest)

    def test_real_historical_baseline_unchanged(self):
        root=Path(config.__file__).resolve().parents[2]
        result=disk.preservation(root,root/'docs/sq01-preservation.json')
        self.assertEqual(result['changed_files'],[])
        self.assertEqual(result['checked_files'],409)

    def test_fresh_process_forbidden_input_and_network_audit(self):
        for relative in ['data/brainstorming/week3_papers_metadata.tsv','data/icraft/synthetic.txt']:
            path=self.root/relative;path.parent.mkdir(parents=True,exist_ok=True);path.write_text('synthetic forbidden',encoding='utf-8')
        script=r'''
import sys,tempfile
from pathlib import Path
sys.path.insert(0,sys.argv[1])
def audit(event,args):
    if event.startswith(('socket.','urllib.')):raise AssertionError('Network forbidden')
    if event=='open' and isinstance(args[0],(str,bytes)):
        value=str(args[0]).casefold()
        if 'week3_papers_metadata.tsv' in value or 'icraft' in value:raise AssertionError('Evaluation input forbidden')
sys.addaudithook(audit)
from deathmap_ai import sq01_plan as p,sq01_omicsdi as o
folder=Path(sys.argv[2])/'audit-output';folder.mkdir()
s=o.initial(p.digest(p.build_plan()))
o.run(folder,s,s['plan_digest'],lambda *args:{'http_status':200,'headers':{},'body':b'{"count":0,"datasets":[]}'},sleep=lambda _:None,emit=lambda _:None)
assert s['status']=='complete'
assert 'deathmap_ai.discovery_v02' not in sys.modules
assert 'deathmap_ai.shared_search' not in sys.modules
'''
        result=subprocess.run([sys.executable,'-B','-c',script,str(Path(config.__file__).resolve().parents[1]),str(self.root)],capture_output=True,text=True,timeout=30)
        self.assertEqual(result.returncode,0,result.stderr)


if __name__=='__main__':unittest.main()
